- name: '🔒not compatible'
  color: 'd4d4d4'
- name: '📡help wanted'
  color: 'f0dc59'
- name: '📡duplicate'
  description: 'This issue or pull request already exists'
  color: 'f0dc59'
- name: '📡invalid'
  description: 'This issue or pull request is invalid'
  color: 'f0dc59'
- name: '📡wrong'
  description: 'This issue or pull request is wrong'
  color: 'f0dc59'
- name: '🏃high'
  color: 'fc032c'
- name: '🚶low'
  color: 'f7b2bd'
- name: '🐛bug'
  color: 'ff0026'
- name: '✏️Typo'
  color: 'FFED4B'
- name: '✏️Accessibility'
  color: 'FFED4B'
- name: '✏️Content'
  color: 'FFED4B'
- name: '✏️Media'
  color: 'FFED4B'
- name: '🧤B - Chrome'
  color: '84C9FF'
- name: '🧤B - Edge'
  color: '84C9FF'
- name: '🧤B - Firefox'
  color: '84C9FF'
- name: '🧤B - Safari'
  color: '84C9FF'
- name: '👮security'
  color: 'ff0026'
- name: '✨design'
  color: 'ee9cff'
- name: '✨improvement'
  color: 'ee9cff'
- name: '✨enhancement'
  color: 'ee9cff'
- name: '🔮workflow (gh-actions)'
  color: 'ee9cff'
- name: '🔮dependabot: update(npm)'
  color: 'ee9cff'
- name: '🔮dependabot: update(gh-actions)'
  color: 'ee9cff'
- name: '🔮dependabot: security'
  color: 'ee9cff'
- name: '💃no context'
  description: 'No Context, 内容が薄いもう少し詳しいものがほしいものに付与'
  color: 'f0dc59'
- name: '💃feature request'
  description: 'This issue or pull request is invalid'
  color: 'f0dc59'
- name: '🌂good first issue'
  description: '君でもできる!さあやろう!'
  color: '69f5a8'
