env:
  node: true
  es2021: true
extends:
  - 'next/core-web-vitals'
  - 'prettier'
  - plugin:mdx/recommended
plugins:
  - '@typescript-eslint'
  - 'simple-import-sort'
  - 'import'
rules:
  'simple-import-sort/imports': 'error'
  'simple-import-sort/exports': 'error'
  'max-params': 'error'
  'import/first': 'error'
  'import/no-duplicates': 'error'
  # TODO: 必要に応じてルールを追加する
  #  https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
  'import/order': [2, { 'alphabetize': { 'order': 'asc' } }]
settings:
  'mdx/code-blocks': true
