blank_issues_enabled: true
contact_links:
  - name: 新生はらちょの不具合
    url: https://github.com/approvers/OreOreBot2/issues/new?assignees=&labels=bug&template=bug-report.md&title=bug%3A+
    about: 新生はらちょの不具合はこちらから報告してください。
